apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production-integrate

namePrefix: production-

commonLabels:
  app: api
  environment: production

resources:
- ../../base
- autoscaler.yaml
- secrets.yaml
- service-account.yaml

patchesJson6902:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: api-ingress
- path: redis-patch.yaml
  target:
    kind: StatefulSet
    name: redis-storage
