apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-integrate

namePrefix: staging-

commonLabels:
  app: client
  environment: staging

resources:
  - ../../base
  - autoscaler.yaml

patchesJson6902:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: client
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: client-ingress
  - path: service-patch.yaml
    target:
      kind: Service
      name: client-nodeport
